export interface Country {
  label: string;    // "🇺🇸 United States (+1)"
  value: string;    // "US"
  dialCode: string; // "+1"
}

export const countries: Country[] = [
  { label: "🇦🇫 Afghanistan (+93)", value: "AF", dialCode: "+93" },
  { label: "🇦🇱 Albania (+355)", value: "AL", dialCode: "+355" },
  { label: "🇩🇿 Algeria (+213)", value: "DZ", dialCode: "+213" },
  { label: "🇦🇸 American Samoa (+1-684)", value: "AS", dialCode: "+1-684" },
  { label: "🇦🇩 Andorra (+376)", value: "AD", dialCode: "+376" },
  { label: "🇦🇴 Angola (+244)", value: "AO", dialCode: "+244" },
  { label: "🇦🇮 Anguilla (+1-264)", value: "AI", dialCode: "+1-264" },
  { label: "🇦🇬 Antigua and Barbuda (+1-268)", value: "AG", dialCode: "+1-268" },
  { label: "🇦🇷 Argentina (+54)", value: "AR", dialCode: "+54" },
  { label: "🇦🇲 Armenia (+374)", value: "AM", dialCode: "+374" },
  { label: "🇦🇼 Aruba (+297)", value: "AW", dialCode: "+297" },
  { label: "🇦🇺 Australia (+61)", value: "AU", dialCode: "+61" },
  { label: "🇦🇹 Austria (+43)", value: "AT", dialCode: "+43" },
  { label: "🇦🇿 Azerbaijan (+994)", value: "AZ", dialCode: "+994" },
  { label: "🇧🇸 Bahamas (+1-242)", value: "BS", dialCode: "+1-242" },
  { label: "🇧🇭 Bahrain (+973)", value: "BH", dialCode: "+973" },
  { label: "🇧🇩 Bangladesh (+880)", value: "BD", dialCode: "+880" },
  { label: "🇧🇧 Barbados (+1-246)", value: "BB", dialCode: "+1-246" },
  { label: "🇧🇾 Belarus (+375)", value: "BY", dialCode: "+375" },
  { label: "🇧🇪 Belgium (+32)", value: "BE", dialCode: "+32" },
  { label: "🇧🇿 Belize (+501)", value: "BZ", dialCode: "+501" },
  { label: "🇧🇯 Benin (+229)", value: "BJ", dialCode: "+229" },
  { label: "🇧🇲 Bermuda (+1-441)", value: "BM", dialCode: "+1-441" },
  { label: "🇧🇹 Bhutan (+975)", value: "BT", dialCode: "+975" },
  { label: "🇧🇴 Bolivia (+591)", value: "BO", dialCode: "+591" },
  { label: "🇧🇦 Bosnia and Herzegovina (+387)", value: "BA", dialCode: "+387" },
  { label: "🇧🇼 Botswana (+267)", value: "BW", dialCode: "+267" },
  { label: "🇧🇷 Brazil (+55)", value: "BR", dialCode: "+55" },
  { label: "🇧🇳 Brunei Darussalam (+673)", value: "BN", dialCode: "+673" },
  { label: "🇧🇬 Bulgaria (+359)", value: "BG", dialCode: "+359" },
  { label: "🇧🇫 Burkina Faso (+226)", value: "BF", dialCode: "+226" },
  { label: "🇧🇮 Burundi (+257)", value: "BI", dialCode: "+257" },
  { label: "🇰🇭 Cambodia (+855)", value: "KH", dialCode: "+855" },
  { label: "🇨🇲 Cameroon (+237)", value: "CM", dialCode: "+237" },
  { label: "🇨🇦 Canada (+1)", value: "CA", dialCode: "+1" },
  { label: "🇨🇻 Cape Verde (+238)", value: "CV", dialCode: "+238" },
  { label: "🇰🇾 Cayman Islands (+1-345)", value: "KY", dialCode: "+1-345" },
  { label: "🇨🇫 Central African Republic (+236)", value: "CF", dialCode: "+236" },
  { label: "🇹🇩 Chad (+235)", value: "TD", dialCode: "+235" },
  { label: "🇨🇱 Chile (+56)", value: "CL", dialCode: "+56" },
  { label: "🇨🇳 China (+86)", value: "CN", dialCode: "+86" },
  { label: "🇨🇴 Colombia (+57)", value: "CO", dialCode: "+57" },
  { label: "🇰🇲 Comoros (+269)", value: "KM", dialCode: "+269" },
  { label: "🇨🇬 Congo (+242)", value: "CG", dialCode: "+242" },
  { label: "🇨🇩 Congo, Dem. Republic (+243)", value: "CD", dialCode: "+243" },
  { label: "🇨🇷 Costa Rica (+506)", value: "CR", dialCode: "+506" },
  { label: "🇨🇮 Côte d'Ivoire (+225)", value: "CI", dialCode: "+225" },
  { label: "🇭🇷 Croatia (+385)", value: "HR", dialCode: "+385" },
  { label: "🇨🇺 Cuba (+53)", value: "CU", dialCode: "+53" },
  { label: "🇨🇾 Cyprus (+357)", value: "CY", dialCode: "+357" },
  { label: "🇨🇿 Czech Republic (+420)", value: "CZ", dialCode: "+420" },
  { label: "🇩🇰 Denmark (+45)", value: "DK", dialCode: "+45" },
  { label: "🇩🇯 Djibouti (+253)", value: "DJ", dialCode: "+253" },
  { label: "🇩🇲 Dominica (+1-767)", value: "DM", dialCode: "+1-767" },
  { label: "🇩🇴 Dominican Republic (+1-809)", value: "DO", dialCode: "+1-809" },
  { label: "🇪🇨 Ecuador (+593)", value: "EC", dialCode: "+593" },
  { label: "🇪🇬 Egypt (+20)", value: "EG", dialCode: "+20" },
  { label: "🇸🇻 El Salvador (+503)", value: "SV", dialCode: "+503" },
  { label: "🇬🇶 Equatorial Guinea (+240)", value: "GQ", dialCode: "+240" },
  { label: "🇪🇷 Eritrea (+291)", value: "ER", dialCode: "+291" },
  { label: "🇪🇪 Estonia (+372)", value: "EE", dialCode: "+372" },
  { label: "🇪🇹 Ethiopia (+251)", value: "ET", dialCode: "+251" },
  { label: "🇫🇯 Fiji (+679)", value: "FJ", dialCode: "+679" },
  { label: "🇫🇮 Finland (+358)", value: "FI", dialCode: "+358" },
  { label: "🇫🇷 France (+33)", value: "FR", dialCode: "+33" },
  { label: "🇬🇦 Gabon (+241)", value: "GA", dialCode: "+241" },
  { label: "🇬🇲 Gambia (+220)", value: "GM", dialCode: "+220" },
  { label: "🇬🇪 Georgia (+995)", value: "GE", dialCode: "+995" },
  { label: "🇩🇪 Germany (+49)", value: "DE", dialCode: "+49" },
  { label: "🇬🇭 Ghana (+233)", value: "GH", dialCode: "+233" },
  { label: "🇬🇷 Greece (+30)", value: "GR", dialCode: "+30" },
  { label: "🇬🇩 Grenada (+1-473)", value: "GD", dialCode: "+1-473" },
  { label: "🇬🇹 Guatemala (+502)", value: "GT", dialCode: "+502" },
  { label: "🇬🇳 Guinea (+224)", value: "GN", dialCode: "+224" },
  { label: "🇬🇼 Guinea-Bissau (+245)", value: "GW", dialCode: "+245" },
  { label: "🇬🇾 Guyana (+592)", value: "GY", dialCode: "+592" },
  { label: "🇭🇹 Haiti (+509)", value: "HT", dialCode: "+509" },
  { label: "🇭🇳 Honduras (+504)", value: "HN", dialCode: "+504" },
  { label: "🇭🇰 Hong Kong (+852)", value: "HK", dialCode: "+852" },
  { label: "🇭🇺 Hungary (+36)", value: "HU", dialCode: "+36" },
  { label: "🇮🇸 Iceland (+354)", value: "IS", dialCode: "+354" },
  { label: "🇮🇳 India (+91)", value: "IN", dialCode: "+91" },
  { label: "🇮🇩 Indonesia (+62)", value: "ID", dialCode: "+62" },
  { label: "🇮🇷 Iran (+98)", value: "IR", dialCode: "+98" },
  { label: "🇮🇶 Iraq (+964)", value: "IQ", dialCode: "+964" },
  { label: "🇮🇪 Ireland (+353)", value: "IE", dialCode: "+353" },
  { label: "🇮🇱 Israel (+972)", value: "IL", dialCode: "+972" },
  { label: "🇮🇹 Italy (+39)", value: "IT", dialCode: "+39" },
  { label: "🇯🇲 Jamaica (+1-876)", value: "JM", dialCode: "+1-876" },
  { label: "🇯🇵 Japan (+81)", value: "JP", dialCode: "+81" },
  { label: "🇯🇴 Jordan (+962)", value: "JO", dialCode: "+962" },
  { label: "🇰🇿 Kazakhstan (+7)", value: "KZ", dialCode: "+7" },
  { label: "🇰🇪 Kenya (+254)", value: "KE", dialCode: "+254" },
  { label: "🇰🇮 Kiribati (+686)", value: "KI", dialCode: "+686" },
  { label: "🇰🇵 North Korea (+850)", value: "KP", dialCode: "+850" },
  { label: "🇰🇷 South Korea (+82)", value: "KR", dialCode: "+82" },
  { label: "🇰🇼 Kuwait (+965)", value: "KW", dialCode: "+965" },
  { label: "🇰🇬 Kyrgyzstan (+996)", value: "KG", dialCode: "+996" },
  { label: "🇱🇦 Laos (+856)", value: "LA", dialCode: "+856" },
  { label: "🇱🇻 Latvia (+371)", value: "LV", dialCode: "+371" },
  { label: "🇱🇧 Lebanon (+961)", value: "LB", dialCode: "+961" },
  { label: "🇱🇸 Lesotho (+266)", value: "LS", dialCode: "+266" },
  { label: "🇱🇷 Liberia (+231)", value: "LR", dialCode: "+231" },
  { label: "🇱🇾 Libya (+218)", value: "LY", dialCode: "+218" },
  { label: "🇱🇮 Liechtenstein (+423)", value: "LI", dialCode: "+423" },
  { label: "🇱🇹 Lithuania (+370)", value: "LT", dialCode: "+370" },
  { label: "🇱🇺 Luxembourg (+352)", value: "LU", dialCode: "+352" },
  { label: "🇲🇴 Macao (+853)", value: "MO", dialCode: "+853" },
  { label: "🇲🇰 Macedonia (+389)", value: "MK", dialCode: "+389" },
  { label: "🇲🇬 Madagascar (+261)", value: "MG", dialCode: "+261" },
  { label: "🇲🇼 Malawi (+265)", value: "MW", dialCode: "+265" },
  { label: "🇲🇾 Malaysia (+60)", value: "MY", dialCode: "+60" },
  { label: "🇲🇻 Maldives (+960)", value: "MV", dialCode: "+960" },
  { label: "🇲🇱 Mali (+223)", value: "ML", dialCode: "+223" },
  { label: "🇲🇹 Malta (+356)", value: "MT", dialCode: "+356" },
  { label: "🇲🇭 Marshall Islands (+692)", value: "MH", dialCode: "+692" },
  { label: "🇲🇷 Mauritania (+222)", value: "MR", dialCode: "+222" },
  { label: "🇲🇺 Mauritius (+230)", value: "MU", dialCode: "+230" },
  { label: "🇲🇽 Mexico (+52)", value: "MX", dialCode: "+52" },
  { label: "🇫🇲 Micronesia (+691)", value: "FM", dialCode: "+691" },
  { label: "🇲🇩 Moldova (+373)", value: "MD", dialCode: "+373" },
  { label: "🇲🇨 Monaco (+377)", value: "MC", dialCode: "+377" },
  { label: "🇲🇳 Mongolia (+976)", value: "MN", dialCode: "+976" },
  { label: "🇲🇪 Montenegro (+382)", value: "ME", dialCode: "+382" },
  { label: "🇲🇦 Morocco (+212)", value: "MA", dialCode: "+212" },
  { label: "🇲🇿 Mozambique (+258)", value: "MZ", dialCode: "+258" },
  { label: "🇲🇲 Myanmar (+95)", value: "MM", dialCode: "+95" },
  { label: "🇳🇦 Namibia (+264)", value: "NA", dialCode: "+264" },
  { label: "🇳🇷 Nauru (+674)", value: "NR", dialCode: "+674" },
  { label: "🇳🇵 Nepal (+977)", value: "NP", dialCode: "+977" },
  { label: "🇳🇱 Netherlands (+31)", value: "NL", dialCode: "+31" },
  { label: "🇳🇿 New Zealand (+64)", value: "NZ", dialCode: "+64" },
  { label: "🇳🇮 Nicaragua (+505)", value: "NI", dialCode: "+505" },
  { label: "🇳🇪 Niger (+227)", value: "NE", dialCode: "+227" },
  { label: "🇳🇬 Nigeria (+234)", value: "NG", dialCode: "+234" },
  { label: "🇳🇴 Norway (+47)", value: "NO", dialCode: "+47" },
  { label: "🇴🇲 Oman (+968)", value: "OM", dialCode: "+968" },
  { label: "🇵🇰 Pakistan (+92)", value: "PK", dialCode: "+92" },
  { label: "🇵🇼 Palau (+680)", value: "PW", dialCode: "+680" },
  { label: "🇵🇦 Panama (+507)", value: "PA", dialCode: "+507" },
  { label: "🇵🇬 Papua New Guinea (+675)", value: "PG", dialCode: "+675" },
  { label: "🇵🇾 Paraguay (+595)", value: "PY", dialCode: "+595" },
  { label: "🇵🇪 Peru (+51)", value: "PE", dialCode: "+51" },
  { label: "🇵🇭 Philippines (+63)", value: "PH", dialCode: "+63" },
  { label: "🇵🇱 Poland (+48)", value: "PL", dialCode: "+48" },
  { label: "🇵🇹 Portugal (+351)", value: "PT", dialCode: "+351" },
  { label: "🇶🇦 Qatar (+974)", value: "QA", dialCode: "+974" },
  { label: "🇷🇴 Romania (+40)", value: "RO", dialCode: "+40" },
  { label: "🇷🇺 Russia (+7)", value: "RU", dialCode: "+7" },
  { label: "🇷🇼 Rwanda (+250)", value: "RW", dialCode: "+250" },
  { label: "🇰🇳 St. Kitts and Nevis (+1-869)", value: "KN", dialCode: "+1-869" },
  { label: "🇱🇨 St. Lucia (+1-758)", value: "LC", dialCode: "+1-758" },
  { label: "🇻🇨 St. Vincent (+1-784)", value: "VC", dialCode: "+1-784" },
  { label: "🇼🇸 Samoa (+685)", value: "WS", dialCode: "+685" },
  { label: "🇸🇲 San Marino (+378)", value: "SM", dialCode: "+378" },
  { label: "🇸🇹 Sao Tome and Principe (+239)", value: "ST", dialCode: "+239" },
  { label: "🇸🇦 Saudi Arabia (+966)", value: "SA", dialCode: "+966" },
  { label: "🇸🇳 Senegal (+221)", value: "SN", dialCode: "+221" },
  { label: "🇷🇸 Serbia (+381)", value: "RS", dialCode: "+381" },
  { label: "🇸🇨 Seychelles (+248)", value: "SC", dialCode: "+248" },
  { label: "🇸🇱 Sierra Leone (+232)", value: "SL", dialCode: "+232" },
  { label: "🇸🇬 Singapore (+65)", value: "SG", dialCode: "+65" },
  { label: "🇸🇰 Slovakia (+421)", value: "SK", dialCode: "+421" },
  { label: "🇸🇮 Slovenia (+386)", value: "SI", dialCode: "+386" },
  { label: "🇸🇧 Solomon Islands (+677)", value: "SB", dialCode: "+677" },
  { label: "🇸🇴 Somalia (+252)", value: "SO", dialCode: "+252" },
  { label: "🇿🇦 South Africa (+27)", value: "ZA", dialCode: "+27" },
  { label: "🇸🇸 South Sudan (+211)", value: "SS", dialCode: "+211" },
  { label: "🇪🇸 Spain (+34)", value: "ES", dialCode: "+34" },
  { label: "🇱🇰 Sri Lanka (+94)", value: "LK", dialCode: "+94" },
  { label: "🇸🇩 Sudan (+249)", value: "SD", dialCode: "+249" },
  { label: "🇸🇷 Suriname (+597)", value: "SR", dialCode: "+597" },
  { label: "🇸🇿 Swaziland (+268)", value: "SZ", dialCode: "+268" },
  { label: "🇸🇪 Sweden (+46)", value: "SE", dialCode: "+46" },
  { label: "🇨🇭 Switzerland (+41)", value: "CH", dialCode: "+41" },
  { label: "🇸🇾 Syria (+963)", value: "SY", dialCode: "+963" },
  { label: "🇹🇼 Taiwan (+886)", value: "TW", dialCode: "+886" },
  { label: "🇹🇯 Tajikistan (+992)", value: "TJ", dialCode: "+992" },
  { label: "🇹🇿 Tanzania (+255)", value: "TZ", dialCode: "+255" },
  { label: "🇹🇭 Thailand (+66)", value: "TH", dialCode: "+66" },
  { label: "🇹🇱 Timor-Leste (+670)", value: "TL", dialCode: "+670" },
  { label: "🇹🇬 Togo (+228)", value: "TG", dialCode: "+228" },
  { label: "🇹🇴 Tonga (+676)", value: "TO", dialCode: "+676" },
  { label: "🇹🇹 Trinidad and Tobago (+1-868)", value: "TT", dialCode: "+1-868" },
  { label: "🇹🇳 Tunisia (+216)", value: "TN", dialCode: "+216" },
  { label: "🇹🇷 Turkey (+90)", value: "TR", dialCode: "+90" },
  { label: "🇹🇲 Turkmenistan (+993)", value: "TM", dialCode: "+993" },
  { label: "🇹🇻 Tuvalu (+688)", value: "TV", dialCode: "+688" },
  { label: "🇺🇬 Uganda (+256)", value: "UG", dialCode: "+256" },
  { label: "🇺🇦 Ukraine (+380)", value: "UA", dialCode: "+380" },
  { label: "🇦🇪 United Arab Emirates (+971)", value: "AE", dialCode: "+971" },
  { label: "🇬🇧 United Kingdom (+44)", value: "GB", dialCode: "+44" },
  { label: "🇺🇸 United States (+1)", value: "US", dialCode: "+1" },
  { label: "🇺🇾 Uruguay (+598)", value: "UY", dialCode: "+598" },
  { label: "🇺🇿 Uzbekistan (+998)", value: "UZ", dialCode: "+998" },
  { label: "🇻🇺 Vanuatu (+678)", value: "VU", dialCode: "+678" },
  { label: "🇻🇪 Venezuela (+58)", value: "VE", dialCode: "+58" },
  { label: "🇻🇳 Vietnam (+84)", value: "VN", dialCode: "+84" },
  { label: "🇾🇪 Yemen (+967)", value: "YE", dialCode: "+967" },
  { label: "🇿🇲 Zambia (+260)", value: "ZM", dialCode: "+260" },
  { label: "🇿🇼 Zimbabwe (+263)", value: "ZW", dialCode: "+263" },
];